############################################################################################################################
##                                                  输送线配置                                                             ##
############################################################################################################################
#输送线
conveyor_line:
  #设备编号
  - code: K10
    #启用状态，设置为false则不读取配置
    #类型：Boolean
    #默认值：true
    enable: false
    #输送线关联点位
    #一台输送线可能有多层取放货点
    relevancy_point:
      #点位别名（String）
      - PO1
      - PO2
    #输送线对接点
    #和输送线关联点位不可相同
    #实现原理：输送线点位被占用，所以AGV只能在前一个点位等待点位释放才能去取放货，因此变相实现了AGV等待取放货信号
    docking_point: 1-41
    #取货模式 0任务下发前询问是否可取货 1在对接点询问是否可取货
    pickup_mode: 1
    #卸货模式 0任务下发前询问是否可卸货 1在对接点询问是否可卸货
    unload_mode: 1
    #对接提前点
    docking_advance: 2
  #设备编号
  - code: K11
    #启用状态，设置为false则不读取配置
    #类型：Boolean
    #默认值：true
    enable: false
    #输送线关联点位
    #一台输送线可能有多层取放货点
    relevancy_point:
      #点位别名（String）
      - PO3
      - PO4
    #输送线对接点
    #和输送线关联点位不可相同
    #实现原理：输送线点位被占用，所以AGV只能在前一个点位等待点位释放才能去取放货，因此变相实现了AGV等待取放货信号
    docking_point: 1-93
    #取货模式 0任务下发前询问是否可取货 1在对接点询问是否可取货
    pickup_mode: 1
    #卸货模式 0任务下发前询问是否可卸货 1在对接点询问是否可卸货
    unload_mode: 1
    #对接提前点
    docking_advance: 2

############################################################################################################################
##                                                  自动门配置                                                             ##
############################################################################################################################
#自动门
automatic_doors:
  #设备编号
  - code: K10_Door
    #启用状态，设置为false则不读取配置
    #类型：Boolean
    #默认值：true
    enable: false
    #自动门点位
    point: 1-24
    #对接类型 0穿越 1进出
    #穿越可以理解为AGV需要穿过这个自动门然后根据延迟执行关门
    #进出可以理解为AGV需要进入这个自动门进行取放货然后从自动门出来再根据延迟执行关门（比穿越类型消耗更多性能）
    #默认值：0
    type: 0
    #自动门开门提前点
    #当AGV前进到距离内的点位，调度将触发自动门的开门功能
    #举例：距离点数是2，查找设备点位3父子点位的长度，那么查询到[1,2,3,4,5]点位数组，如果数组内有AGV规划的点位，那么触发开门功能
    #默认值：2
    #最小条件：1
    open_advance: 1
    #自动门关门延迟点
    #当AGV离开自动门的距离外的点位，调度将触发自动门的关门功能
    #举例：距离点数是1，查找设备点位3父子点位的长度，那么查询到[2,3,4]点位数组，如果数组内没有被占用的点位，那么触发关门功能
    #默认值：1
    #最小条件：0
    close_delay: 1

############################################################################################################################
##                                                   电梯配置                                                              ##
############################################################################################################################
#电梯
elevators:
  #设备编号
  - code: elevator_left
    #启用状态，设置为false则不读取配置
    #类型：Boolean
    #默认值：true
    enable: false
    #设备的所有电梯门
    #电梯的占用点位是电梯的内门和外门设备编号
    #格式：{电梯门编号},{地图编号-点位}
    occupancys:
      - elevator_left,1-66
      - elevator_left,1-70
    #电梯传送点
    #不同的地图可以有多个不同的传送点，方便AGV在不同的地图间切换
    #传送点是电梯内部的点位，比如1楼的点位是1-29，2楼的点位是2-1
    #格式：{地图编号-点位},{地图编号-点位}
    teleports:
      # 传送ID
      #{teleport}_{起点楼层}_{终点楼层}
      - id: teleport_1_2
        origin: 1-29
        destin: 2-1
        #是否是双向传送点，举例这个电梯可以从1楼到2楼，又可以从2楼到1楼
        #默认值：true
        bidirectional: true
    #交互点
    interactions:
      #传送ID
      #{teleport}_{起点楼层}_{终点楼层}
      - teleport_1_2:
          #交互开始
          start:
            #交互点位
            point: 1-37
            #需开门的集合
            door:
              - elevator_left
          #交互结束
          end:
            #交互点位
            point: 2-40
            #需关门的集合
            door:
              - elevator_left

############################################################################################################################
##                                                  风淋室配置                                                             ##
############################################################################################################################
#风淋室
airShowers:
  #设备编号
  - code: 2F_Left_out
    #启用状态，设置为false则不读取配置
    #类型：Boolean
    #默认值：true
    enable: false
    #风淋室点位
    point: 1-25
    #设备的所有占用点
    #风淋室的占用点位是自动门的点位
    occupancys:
      - 2F_Left_out,1-42
      - 2F_Left_in,1-24
    #交互点
    interactions:
      #从哪个门进入风淋室，值为自动门编号
      - 2F_Left_out:
          #交互开始
          start:
            #开始门
            door:
              - 2F_Left_out
            #交互点位
            point: 1-43
          #交互结束
          end:
            #结束门
            door:
              - 2F_Left_in
            #交互点位
            point: 1-23
      #从哪个门进入风淋室，值为自动门编号
      - 2F_Left_in:
          #交互开始
          start:
            #前门
            door:
              - 2F_Left_in
            #动作点位
            point: 1-23
          #交互结束
          end:
            #后门
            door:
              - 2F_Left_out
            #动作点位
            point: 1-43