############################################################################################################################
##                                            任务相关配置(重启生效)                                                        ##
############################################################################################################################
#任务通用配置
task_common:
  #任务分配模式 -1自定义 0距离优先 1电量优先 2最近停靠优先 3起点指定 4终点指定 5起点区域指定 6终点区域指定
  #距离优先：寻找所有空闲AGV选择最近的AGV执行任务
  #电量优先：寻找所有空闲AGV选择电量高的AGV执行任务
  #最近停靠优先：寻找最近的停靠点的AGV执行任务，如果停靠点无AGV则等待，如果AGV在充电则不会中断充电任务而是等AGV充电完成
  #起点指定：根据AGV绑定的任务起点接取任务，如果AGV忙碌则等待
  #终点指定：根据AGV绑定的任务终点接取任务，如果AGV忙碌则等待
  #起点区域指定：根据AGV绑定的任务起点区域接取任务，如果AGV忙碌则等待
  #终点区域指定：根据AGV绑定的任务终点区域接取任务，如果AGV忙碌则等待
  #自定义：根据需求自定义，一般由于开发人员针对不同项目开发好后配置的，如您不懂请勿选择此项
  #类型：int
  #默认值：1
  task_distribute_mode: 0
  #任务起点指定AGV，AGV将只接取设置中的任务起点点位的任务
  #生效条件：task_distribute_mode : 3
  #多地图格式：{地图编号-点位编号}（String）（不能重复） : 多个AGV_ID（String）（英文逗号隔开）
  task_origin_specify:
    1-1: 2,3
  #任务终点指定AGV，AGV将只接取设置的任务终点点位的任务
  #生效条件：task_distribute_mode : 4
  #多地图格式：{地图编号-点位编号}（String）（不能重复） : 多个AGV_ID（String）（英文逗号隔开）
  task_destin_specify:
    1-5: 2,3
  #任务起点区域指定AGV，AGV将只接取设置的任务起点区域的任务
  #生效条件：task_distribute_mode : 5
  #格式：区域编号（String）（不能重复） : 多个AGV_ID（String）（英文逗号隔开）
  task_origin_area:
    区域1: 2,3
  #任务终点区域指定AGV，AGV将只接取设置的任务终点区域的任务
  #生效条件：task_distribute_mode : 6
  #格式：区域编号（String）（不能重复） : 多个AGV_ID（String）（英文逗号隔开）
  task_destin_area:
    区域1: 2,3

############################################################################################################################
##                                            正则相关配置(重启生效)                                                        ##
############################################################################################################################
#正则表达式是一种用于匹配和操作文本的强大工具，它是由一系列字符和特殊字符组成的模式，用于描述要匹配的文本模式
#正则表达式可以在文本中查找、替换、提取和验证特定的模式
#建议询问AI生成和验证指定的正则表达式，避免出现错误
#正则表达式详解：https://www.runoob.com/regexp/regexp-tutorial.html
regex_common:
  #点位别名,任务起点或终点属于某个地图的点位时，可以配置别名，系统会以正则来匹配地图点位
  #格式：正则表达式（String）（不能重复） : 地图号-点位（String）（英文逗号隔开）
  task_piont_alias:
    0: 1-0
    U-001-L: 1-13
    U-002-L: 1-20
    U-003-L: 1-22
    U-004-L: 1-27
    U-005-L: 1-29
    U-006-L: 1-34
    U-007-L: 1-36
    U-008-L: 1-41
    U-009-L: 1-43
    U-010-L: 1-48
    P-L-001: 1-7

    U-001-U: 1-15
    U-002-U: 1-21
    U-003-U: 1-23
    U-004-U: 1-28
    U-005-U: 1-30
    U-006-U: 1-35
    U-007-U: 1-37
    U-008-U: 1-42
    U-009-U: 1-44
    U-010-U: 1-49
    P-U-001: 1-5

  #AGV起点动作参数，系统会以任务起点来匹配正则表达式，完全匹配则使用对应的动作和参数
  #当系统匹配不成功时，系统将使用默认动作:0和参数:0
  #格式：正则表达式 [点位别名 + 托盘类型（非必须）]（String）（不能重复） : 动作,参数（英文逗号隔开）
  #系统按 [点位别名 - 任务类型 - 托盘类型] -> [点位别名 - 任务类型] -> [点位别名] 的顺序匹配
  #任务类型：0搬运任务 1充电任务 2停靠任务 3临时任务 4避让任务
  #动作：1取货 2放货 3充电 4对接设备
  origin_action_parameter:
    U-001-L: 1,0
    U-002-L: 1,0
    U-003-L: 1,0
    U-004-L: 1,0
    U-005-L: 1,0
    U-006-L: 1,0
    U-007-L: 1,0
    U-008-L: 1,0
    U-009-L: 1,0
    U-010-L: 1,0

    P-L-001: 1,0

  #AGV终点动作参数，系统会以任务终点来匹配正则表达式，完全匹配则使用对应的动作和参数
  #当系统匹配不成功时，系统将使用默认动作:0和参数:0
  #格式：正则表达式 [点位别名 + 托盘类型（非必须）]（String）（不能重复） : 动作,参数（英文逗号隔开）
  #系统按 [点位别名 - 任务类型 - 托盘类型] -> [点位别名 - 任务类型] -> [点位别名] 的顺序匹配
  #动作：1取货 2放货 3充电 4对接设备
  destin_action_parameter:
    U-001-U: 2,0
    U-002-U: 2,0
    U-003-U: 2,0
    U-004-U: 2,0
    U-005-U: 2,0
    U-006-U: 2,0
    U-007-U: 2,0
    U-008-U: 2,0
    U-009-U: 2,0
    U-010-U: 2,0

    P-U-002: 2,0
############################################################################################################################
##                                            待机相关配置(重启生效)                                                        ##
############################################################################################################################
standby_common:
  #待机模式 -2不待机 -1自定义 0最近待机点 1绑定待机点
  #AGV运送完任务后，AGV会前往待机点等待新任务
  #不待机：AGV运送完任务后不做任何操作，原地等待新任务
  #最近待机点：AGV运送完任务后前往最近的待机点等待新任务
  #绑定待机点：AGV运送完任务后前往绑定的待机点等待新任务
  #自定义：根据需求自定义，一般由于开发人员针对不同项目开发好后配置的，如您不懂请勿选择此项，对定制需求适用
  #默认值：-2
  standby_mode: 0

  #绑定待机点，AGV空闲后前往绑定的待机点等待新任务
  #生效条件：standby_mode : 1
  #格式：{地图编号-点位}（String）（不能重复） : 多个AGV_ID（String）（英文逗号隔开）
  standby_point_binding:
    1-34: 1
    #  1-25 : 2
    2-30: 5
    2-37: 3

  #待机屏蔽点，AGV在屏蔽点空闲后不再前往待机点待机
  #AGV停止在待机屏蔽点后不接收待机任务，这在与设备联动时非常有用
  #格式：{地图编号-点位}（String）（不能重复） : 多个AGV_ID（String）（英文逗号隔开）
  standby_point_shield:
  #  1-16 : 2

############################################################################################################################
##                                            充电相关配置(重启生效)                                                        ##
############################################################################################################################
charge_common:
  #AGV允许充电阈值，当AGV电量低于等于该值时，将创建充电任务且不再接取新任务
  #单位：百分比 %
  #默认值：20
  allow_charge_power: 20
  #agv最低工作电量，当AGV电量高于等于该值时，有新任务时将中断当前充电任务前往接取任务
  #单位：百分比 %
  #默认值：50
  lowest_work_power: 11
  #下班AGV允许充电阈值，当AGV下班电量低于等于该值时，将创建充电任务
  #单位：百分比 %
  #默认值：20
  allow_charge_power_laidoff: 90
  #允许时间段内的充电阈值，当时间段匹配且电量低于等于该值时，将创建充电任务
  #单位：百分比 %
  #默认值：90
  allow_charge_power_time_period: 90
  #充电桩匹配模式 -2不充电 -1自定义 0距离匹配 1绑定匹配 2类型匹配 3区域匹配 4楼层匹配 5时间段匹配
  #自定义：根据超视堺需求自定义，根据距离和时间段匹配
  #距离匹配：AGV寻找所有充电桩选择最近的充电桩充电
  #绑定匹配：AGV寻找绑定的充电桩选择最近的充电桩充电
  #类型匹配：AGV寻找绑定的充电桩选择指定类型的最近充电桩充电
  #区域匹配：AGV寻找绑定的充电桩选择指定区域的最近充电桩充电
  #楼层匹配：AGV寻找绑定的充电桩选择指定楼层的最近充电桩充电
  #默认值：0
  chargepile_match_mode: 0

  #充电桩绑定AGV，AGV将只能前往绑定的充电桩充电
  #生效条件：chargepile_match_mode : 1
  #格式：充电桩编号（String）（不能重复） : 多个AGV_ID（String）（英文逗号隔开）
  charge_binding_agv:
    3: 2,3
    4: 4
  #充电桩匹配区域，AGV将只能前往指定的充电桩区域充电
  #生效条件：chargepile_match_mode : 3
  #格式：充电桩区域（String）（不能重复） : 多个AGV_ID（String）（英文逗号隔开）
  charge_pile_area:
    ALL: 1,2
  #充电桩匹配楼层，AGV将只能前往指定的楼层充电桩充电
  #生效条件：chargepile_match_mode : 4
  #格式：充电桩楼层（String）（不能重复） : 多个AGV_ID（String）（英文逗号隔开）
  charge_pile_floor:
    1: 1,2
  #充电桩匹配时间段，AGV在规定的时间段内空闲时就去充电 (24小时制)
  #生效条件：chargepile_match_mode : 5
  #格式：开始时间（String）（不能重复） : 结束时间（String）（英文逗号隔开）
  charge_times_agv:
#    5: 8
#    11: 14