############################################################################################################################
##                                          调度系统的地图配置                                                              ##
############################################################################################################################
rcs_map:
  #地图源类型，目前只支持从文件读取，只是为了方便后续扩展
  #配置解释：file 从文件读取地图
  #类型：String
  #默认值：file
  source_type: file
  source_file:
    #地图文件路径，调度启动后将读取该集合的所有地图文件
    #类型：String
    #条件：最少需要有一个地图文件，地图ID不能重复
    #格式：地图ID（int） = 地图文件路径（String）
    #  1: 'F:\slamopto_project\slamopto\maps\sy_test.json'
    1: 'F:\slamopto_project\slamopto\maps\GZ-Foxcoon-CELL-1.json'

############################################################################################################################
##                                          调度系统的连接桥配置（开发中）                                                   ##
############################################################################################################################
#地图桥接点配置，当AGV需要前往不同地图时，需要找到桥接点通行
#两个地图之间有桥接点，当AGV需要前往不同地图时，会选最近的桥接点进行跳转
#
#示例配置：
#bridge_point:
#  1_2:     #桥编号，从地图1到地图2的桥接点，用途是方便调度检索数据
#    - 0  #点位编号（int）
#    - 1  #点位编号（int）
#配置解释：地图编号1有0、1两个待机点
bridge_point:
  #桥编号，{起点地图}_{终点地图}
  1_2:
    #设备编号，桥接点都是需要通过设备进行切换，相当于过河需要船
    equipment_code: elevator_left
    #传送编号，方便从设备交互检索数据
    #{teleport}_{起点楼层}_{终点楼层}
    bridge_id: teleport_1_2
    origin: 1-29
    destin: 2-1
    #是否是双向桥接点，举例可以从地图1到地图2，又可以从地图2到地图1
    #默认值：true
    bidirectional: true

############################################################################################################################
##                                          调度系统的待机点配置                                                            ##
############################################################################################################################
#AGV待机点配置，当AGV需待机时，会从待机点中自动选择一个最近的点位作为待机点
#该配置与地图配置的待机点数据，只有一个配置生效，只有地图配置的待机点无数据才会生效
#
#示例配置：
#standby_point:
#  1:     #地图编号（int），用途是支持不同楼层的待机点位
#    - 0  #点位编号（int）
#    - 1  #点位编号（int）
#配置解释：地图编号1有0、1两个待机点
standby_point:
#  1:
#    - 0

############################################################################################################################
##                                          调度系统的待机屏蔽点配置                                                        ##
############################################################################################################################
#AGV待机屏蔽点配置，当AGV在该点位时，空闲后不再前往待机点待机
#AGV停止在待机屏蔽点后只接收待机以外的任务，与第三方设备联动时非常有用
#
#示例配置：
#standby_shield_point:
#  1:     #地图编号（int），用途是支持不同楼层的待机屏蔽点位
#    - 0  #点位编号（int）
#    - 1  #点位编号（int）
#配置解释：地图编号1有0、1两个待机屏蔽点
standby_shield_point:
#  1:
#    - 0
#    - 1
#    - 2
#    - 3

############################################################################################################################
##                                          调度系统的充电点配置                                                            ##
############################################################################################################################
#AGV充电点配置，当AGV需要充电后自动选择一个充电点
#该配置与地图配置的充电点数据，只有一个配置生效，只有地图配置的充电点无数据才会生效
#
#示例配置：
#charge_point:
#  1:     #地图编号（int），用途是支持不同楼层的充电点位
#    - 0  #点位编号（int）
#    - 1  #点位编号（int）
#配置解释：地图编号1有0、1两个充电点
charge_point:
  1:
    - 0

############################################################################################################################
##                                          调度系统的管制区配置                                                            ##
############################################################################################################################
#AGV管制区配置，当AGV行驶到任意管制区的点位后，其他AGV将无法行驶到该自定编号的所有管制区的点位
#该配置与地图配置的管制区数据，只有一个配置生效，只有地图配置的管制区无数据才会生效
#
#示例配置：
#control_area:
#  1:          #地图编号（int），用途是方便调度检索数据
#    C1:       #自定编号（String）
#      1:      #地图编号（int），用途是是支持管制不同楼层的点位
#        - 0   #点位编号（int）
#        - 1   #点位编号（int）
#配置解释：当AGV行驶到0号点位时，其他AGV将无法行驶到自定编号C1的0号点位和1号点位
control_area:
#  1:
#    C1:
#      1:
#        - 0
#        - 1
#      2:
#        - 0
#        - 1
#    C2:
#      1:
#        - 2
#        - 3
#      2:
#        - 4
#        - 5
#  2:
#    C3:
#      1:
#        - 0
#        - 1
#      2:
#        - 0
#        - 1
#    C4:
#      1:
#        - 0
#        - 1
#      2:
#        - 2
#        - 3

############################################################################################################################
##                                          调度系统的管制点配置                                                            ##
############################################################################################################################
#AGV管制点配置，当AGV行驶到任意管制点后，其他AGV将无法行驶到该点位配置的所有管制点
#【 请注意：该配置与地图配置的管制点数据，只要地图点位没有配置control_point字段的点位，下面配置的该点位就会生效】
#【比如地图的1号点位没有配置control_point字段，下面配置的1号点位就会被读取进系统里】
#
#示例配置：
#control_point:
#  1:         #地图编号（int），用途是方便调度检索数据
#    0:       #管制生效点（int）
#      1:     #地图编号（int），用途是是支持管制不同楼层的点位
#        - 0  #点位编号（int）
#        - 1  #点位编号（int）
#配置解释：当AGV行驶到0号管制生效点时，其他AGV将无法行驶到1号管制生效点的0号点位和1号点位
control_point:
#  1:
#    23:
#      1:
#        - 28
#        - 29
#      2:
#        - 2
#        - 3
#    1:
#      1:
#        - 4
#        - 5
#      2:
#        - 6
#        - 7

############################################################################################################################
##                                          调度系统的避让点配置                                                            ##
############################################################################################################################
#AGV避让点配置，当AGV需避让时，会从避让点中自动选择一个最近的点位作为避让点
#该配置与地图配置的避让点数据，只有一个配置生效，只有地图配置的避让点无数据才会生效
#
#示例配置：
#avoidance_point:
#  1:       #地图编号（int），用途是方便调度检索数据
#    A1:    #自定编号（String）
#      - 0  #点位编号（int）
#      - 1  #点位编号（int）
#配置解释：当AGV在1号地图中需要避让时，从地图编号1中的0、1点位里选择一个最近的点位作为避让点
avoidance_point:
#  1:
#    A1:
#      - 0
#      - 1
#    A2:
#      - 2
#      - 3